sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t leo6d/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leo6d/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-679070613057"
  bucket_path: "docker-react"
  on:
    branch: master
  acess_key_id: $aws-acess-key
  secret_acess_key:
    secure: "$aws-secret-key"
